version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: test_case_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kohkau11999
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper

  celery-worker:
    build: 
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - redis
      - kafka
      - postgres

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - kafka

volumes:
  postgres_data: