"""Initial migration

Revision ID: fad5a949c89a
Revises: 0991b2ddc47e
Create Date: 2025-04-02 18:57:05.503407

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "fad5a949c89a"
down_revision: Union[str, None] = "0991b2ddc47e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
